# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f8844d32b2cbe6c896ec3a1cb895e7c15c4be4d0d2102a627af72cd61f2f7ca53d6be7b57f1cc906e10aaea6b5e433f7f3b4fa028533583ed075d28b1e884a

test:
  secret_key_base: c4d863e564ec045ba4bec36e18a3867d2a03a3feeeb8573040f85a100a70b28d216e541a843fe6706a9ff799c0e0b34cf7a13eb1f17def5792fed2a369b1455c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
